'''
Created on 11.11.2021

@author: michael
'''

VIEW_MODE = 0
EDIT_MODE = 1
A4 = 1
A5 = 2

FILTER_PROPERTY_TITEL = 'Titel'
FILTER_PROPERTY_NAME = 'Name'
FILTER_PROPERTY_ORT = 'Ort'
FILTER_PROPERTY_SYSTEMATIK = 'Systematik'
FILTER_PROPERTY_JAHR_VOR = 'Jahr vor'
FILTER_PROPERTY_SIGNATUR = 'Signatur'
FILTER_PROPERTY_ZDB_MELDUNG = 'ZDB-Meldung'

COMBINATION_AND = 'and'
COMBINATION_OR = 'or'

